jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 3.7
      cache: pip
      before_install:
        - sudo apt-get install libdbus-1-dev libdbus-glib-1-dev --yes
        - chmod +x SpotifyLyrics.pyw
        - pip install --upgrade pip
      before_script:
        - export PYTHONPATH=$PYTHONPATH:$PWD:$PWD/spotify_lyric
      script:
        - cd tests/
        - python -m unittest discover . "*_test.py"
        - cd ..
      before_deploy:
        - pip install pyinstaller
        - pyinstaller SpotifyLyrics.pyw -F -w -i icon.ico --add-data "icon.png:."
      deploy:
        provider: releases
        prerelease: true
        skip_cleanup: true
        token: ${GH_TOKEN}
        file:
          - dist/SpotifyLyrics
        on:
          repo: SimonIT/spotifylyrics
          tags: true
          all_branches: true
    - os: osx
      language: generic
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/.cache/pip
      before_install:
        - brew update
        - pip3 install --upgrade pip
      install:
        - pip3 install -r requirements.txt
      before_script:
        - export PYTHONPATH=$PYTHONPATH:$PWD:$PWD/spotify_lyric
      script:
        - cd tests/
        - python3 -m unittest discover . "*_test.py"
        - cd ..
      before_cache:
        - brew cleanup
      before_deploy:
        - pip3 install pyinstaller
        - pyinstaller SpotifyLyrics.pyw -F -w -i icon.icns --add-data "icon.png:."
        - cd dist/
        - zip -r SpotifyLyrics.app.zip SpotifyLyrics.app
        - cd ..
      deploy:
        provider: releases
        prerelease: true
        skip_cleanup: true
        token: ${GH_TOKEN}
        file:
          - dist/SpotifyLyrics.app.zip
        on:
          repo: SimonIT/spotifylyrics
          tags: true
          all_branches: true
    - os: windows
      language: cpp
      before_install:
        - choco install python --version=3.7.6.20200110
        - export PATH="/C/Python37:/C/Python37/Scripts:$PATH"
      install:
        - python -m pip install -r requirements.txt
      before_script:
        - export PYTHONPATH="$PYTHONPATH;C:\Users\travis\build\SimonIT\spotifylyrics;C:\Users\travis\build\SimonIT\spotifylyrics\spotify_lyric"
      script:
        - cd tests/
        - python -m unittest discover . "*_test.py"
        - cd ..
      before_deploy:
        - python -m pip install pyinstaller
        - pyinstaller SpotifyLyrics.pyw -F -w -i icon.ico --add-data "icon.png;."
      deploy:
        provider: releases
        prerelease: true
        skip_cleanup: true
        token: ${GH_TOKEN}
        file:
          - dist/SpotifyLyrics.exe
        on:
          repo: SimonIT/spotifylyrics
          tags: true
          all_branches: true